export default {
  username: 'input[name=username]',
  password: 'input[name=password]',
  loginButton: 'button[type="submit"]',
  logo: '#logo',
  errorMessage: '.error-message show',
  loginPage: '/login',
  claudePage: '/claude',
  loginContainer: '.login-container',
  usernameText: '[type="text"]',
  passwordText: '[type="password"]',
  aiInput: ':nth-child(1) > .form-control',
  promptFiles: '#promptFiles',
  userInput: '#userInput',
  aiResponse: '#responseContent',
  sendButton: '[onclick="sendBedrockRequest()"]',
  dropdown: '[onclick="showDropdown()"]',
  dataExamplesButton: '#dataExamplesButton',
  copyButton: '#copyButton',
  fileContent: '#fileContent',
  dataSelect: '#dataExamplesSelect',
};